-- Generated from the verified 2026-07-19 D1 vendor/vendor_model configuration.
-- Scope: routing map only. This intentionally does NOT import record/history rows.
-- Prerequisite: import vendor and vendor_model first, preserving their original IDs.
-- Alias compatibility is implemented as separate model rows, not application alias code.
-- Priority semantics (confirmed with the original designer): SMALLER vendor.priority = tried FIRST.
-- Therefore routing_config.upstreams is sorted by vendor.priority ASCENDING.
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (1, 'claude-fable-5', 1, '{}', 'single', '{"upstreams":[{"vendor_id":6,"vendor_model_id":67,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (2, 'claude-opus-4-8', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":73,"enabled":true},{"vendor_id":6,"vendor_model_id":66,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (3, 'claude-sonnet-5', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":38,"enabled":true},{"vendor_id":6,"vendor_model_id":22,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (4, 'deepseek-v4-flash', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":5,"vendor_model_id":20,"enabled":true},{"vendor_id":1,"vendor_model_id":15,"enabled":true},{"vendor_id":2,"vendor_model_id":9,"enabled":true},{"vendor_id":7,"vendor_model_id":29,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (5, 'deepseek-v4-flash:free', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":5,"vendor_model_id":20,"enabled":true},{"vendor_id":1,"vendor_model_id":15,"enabled":true},{"vendor_id":2,"vendor_model_id":9,"enabled":true},{"vendor_id":7,"vendor_model_id":29,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (6, 'deepseek-ai/DeepSeek-V4-Flash', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":5,"vendor_model_id":20,"enabled":true},{"vendor_id":1,"vendor_model_id":15,"enabled":true},{"vendor_id":2,"vendor_model_id":9,"enabled":true},{"vendor_id":7,"vendor_model_id":29,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (7, 'deepseek-v4-pro', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":5,"vendor_model_id":19,"enabled":true},{"vendor_id":10,"vendor_model_id":56,"enabled":true},{"vendor_id":1,"vendor_model_id":14,"enabled":true},{"vendor_id":2,"vendor_model_id":10,"enabled":true},{"vendor_id":7,"vendor_model_id":30,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (8, 'deepseek-ai/DeepSeek-V4-Pro', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":5,"vendor_model_id":19,"enabled":true},{"vendor_id":10,"vendor_model_id":56,"enabled":true},{"vendor_id":1,"vendor_model_id":14,"enabled":true},{"vendor_id":2,"vendor_model_id":10,"enabled":true},{"vendor_id":7,"vendor_model_id":30,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (9, 'gemini-3.1-pro-preview', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":72,"enabled":true},{"vendor_id":6,"vendor_model_id":68,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (10, 'gemini-3.5-flash', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":37,"enabled":true},{"vendor_id":6,"vendor_model_id":25,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (11, 'glm-5.2', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":12,"vendor_model_id":80,"enabled":true},{"vendor_id":5,"vendor_model_id":17,"enabled":true},{"vendor_id":10,"vendor_model_id":57,"enabled":true},{"vendor_id":1,"vendor_model_id":13,"enabled":true},{"vendor_id":2,"vendor_model_id":11,"enabled":true},{"vendor_id":6,"vendor_model_id":71,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (12, 'GLM-5.2', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":12,"vendor_model_id":80,"enabled":true},{"vendor_id":5,"vendor_model_id":17,"enabled":true},{"vendor_id":10,"vendor_model_id":57,"enabled":true},{"vendor_id":1,"vendor_model_id":13,"enabled":true},{"vendor_id":2,"vendor_model_id":11,"enabled":true},{"vendor_id":6,"vendor_model_id":71,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (13, 'zai-org/GLM-5.2', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":12,"vendor_model_id":80,"enabled":true},{"vendor_id":5,"vendor_model_id":17,"enabled":true},{"vendor_id":10,"vendor_model_id":57,"enabled":true},{"vendor_id":1,"vendor_model_id":13,"enabled":true},{"vendor_id":2,"vendor_model_id":11,"enabled":true},{"vendor_id":6,"vendor_model_id":71,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (14, 'gpt-5.4-mini', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":39,"enabled":true},{"vendor_id":6,"vendor_model_id":42,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (15, 'gpt-5.6-luna', 1, '{}', 'single', '{"upstreams":[{"vendor_id":3,"vendor_model_id":76,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (16, 'gpt-5.6-sol', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":74,"enabled":true},{"vendor_id":6,"vendor_model_id":69,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (17, 'gpt-5.6-terra', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":3,"vendor_model_id":75,"enabled":true},{"vendor_id":6,"vendor_model_id":70,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (18, 'grok-4.5', 1, '{}', 'single', '{"upstreams":[{"vendor_id":3,"vendor_model_id":77,"enabled":true}]}');
INSERT INTO model (id, name, enable, prices, routing_mode, routing_config) VALUES (19, 'qwen3.8-max-preview', 1, '{}', 'failover', '{"upstreams":[{"vendor_id":5,"vendor_model_id":53,"enabled":true},{"vendor_id":10,"vendor_model_id":55,"enabled":true}]}');
